name: Docker Image CI

#on:
#  push:
#    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v4

    - name: Extract backend version from CHANGELOG.md
      id: backend_version
      run: |
        VERSION=$(grep -m 1 '^## \[' CHANGELOG.md | sed -E 's/^## \[([^]]+)\].*/\1/')
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    
    - name: Build the frontend Docker image
      run: docker build . --file Dockerfile --tag fabiangnatzig/beerbackend:${{ env.VERSION }} --tag fabiangnatzig/beerbackend:latest
      
    - name: publish the backend Docker image
      run: docker push fabiangnatzig/beerbackend:${{ env.VERSION }}
    - name: publish the latest backend Docker image
      run: docker push fabiangnatzig/beerbackend:latest
