name: Codestyle

on:
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: 22

jobs:
  linting:
    name: Linting with eslint
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Upgrade npm
        run: npm install -g npm@latest

      - name: Install Dependencies
        run: npm ci

      - name: Fix ESLint permissions
        run: chmod +x ./node_modules/.bin/eslint

      - name: Code Linting
        run: npm run lint

  formatting:
    name: Formatting with Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Upgrade npm
        run: npm install -g npm@latest

      - name: Install Dependencies
        run: npm ci

      - name: Code Linting
        run: npx prettier . --check

